### ISSUE TITLE
Unable to import MemTorch

### ISSUE THREAD

**Issue by ameyah** [coreylammie/MemTorch#127]
Hello!

I installed `memtorch-cpu` with `pip install memtorch-cpu` (couldn't install by cloning the source).

However, when I try to import memtorch, it throws the following error:

```
>>> import memtorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ameyah/MemTorch/memtorch/__init__.py", line 4, in <module>
    from memtorch.bh import *
  File "/home/ameyah/MemTorch/memtorch/bh/__init__.py", line 1, in <module>
    from .crossbar import *
  File "/home/ameyah/MemTorch/memtorch/bh/crossbar/__init__.py", line 1, in <module>
    from .Crossbar import *
  File "/home/ameyah/MemTorch/memtorch/bh/crossbar/Crossbar.py", line 18, in <module>
    from .Tile import gen_tiles
  File "/home/ameyah/MemTorch/memtorch/bh/crossbar/Tile.py", line 11, in <module>
    import memtorch_bindings
ImportError: /home/ameyah/.local/lib/python3.9/site-packages/memtorch_bindings.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at3absERKNS_6TensorE
```

Could someone please advise?

**Comment by coreylammie** [comment]
Hi @ameyah,

This appears to be caused by a compatibility issue between your installed `PyTorch` version and the version of `PyTorch` in which `memtorch-cpu` was compiled using. I am planning on releasing version 1.1.6 of `MemTorch` later today (and corresponding pre-built  `memtorch-cpu` wheels), which will be built using version 1.10.0 of `PyTorch`.

The current version of `MemTorch` (at the time of me writing this) is 1.1.5, which was built using version 1.9.0 of `PyTorch`. Could you please confirm the current version of `PyTorch` in which you have installed?

Kind Regards,

Corey.

**Comment by ameyah** [comment]
Hi Corey,

Thanks for looking into it! It makes sense, I have PyTorch 1.10.2 installed.

**Comment by ameyah** [comment]
Works now. Thanks!
