### ISSUE TITLE
Matrix Vector Multiplication

### ISSUE THREAD

**Issue by matifali** [coreylammie/MemTorch#133]
### Discussed in https://github.com/coreylammie/MemTorch/discussions/132

<div type='discussions-op-text'>

<sup>Originally posted by **matifali** March 24, 2022</sup>
Is it possible to use MemTorch to do simple computations without using the PyTorch model structure?
I want to convert a matrix to a memristor crossbar conductances and then multiply it with a vector.</div>

**Comment by coreylammie** [comment]
Hi @matifali,

Apologies for not answering this earlier! Please see the complete example below:

```
import torch
import memtorch
from memtorch.map.Parameter import naive_map
from memtorch.bh.crossbar.Crossbar import init_crossbar
from sklearn import linear_model
from sklearn.metrics import r2_score
import numpy as np


reference_memristor = memtorch.bh.memristor.VTEAM
reference_memristor_params = {
    "time_series_resolution": 1e-10,
    "r_off": 100e3,
    "r_on": 10e3,
}

a = torch.randn(10, 20)
b = torch.randn(20, 10)
expected_product = torch.matmul(a, b)

crossbars, operation = init_crossbar(
    weights=b.T,
    memristor_model=reference_memristor,
    memristor_model_params=reference_memristor_params,
    transistor=True,
    mapping_routine=naive_map,
    programming_routine=None,
    tile_shape=None,
    scheme=memtorch.bh.crossbar.Scheme.DoubleColumn,
)
crossbar_product = torch.matmul(
    a, operation(crossbars, lambda crossbar: crossbar.conductance_matrix)
)
reg = linear_model.LinearRegression(fit_intercept=True).fit(crossbar_product.reshape(-1, 1), expected_product.reshape(-1, 1))
coef = np.array(reg.coef_).item()
intercept = np.array(reg.intercept_).item()
print('Coefficient of determination: %f [%f, %f]' % (r2_score((crossbar_product * coef) + intercept, expected_product), coef, intercept))
```

This returns a correlation coefficient of 1.0, which means that the transformed output of the crossbar (in this case crossbars, as a differential representation scheme is used to represent positive and negative values) is approximately equal to the ideal product.

I have tentatively closed your previous issue, as it looks like it's a duplicate. Please let me know if you have any further questions, or if the above code is unclear!

**Comment by matifali** [comment]
Thank you for the reply. Yes, the code is self-explanatory and works as expected.
Also, I wondered if the same approach can be used to implement memristive multiplications in training.

**Comment by matifali** [comment]
```
a = torch.ones((1,5))
b = torch.full((5,5),5.0)
expected_product = torch.matmul(a, b)

crossbars, operation = init_crossbar(
    weights=b.T,
    memristor_model=reference_memristor,
    memristor_model_params=reference_memristor_params,
    transistor=True,
    mapping_routine=naive_map,
    programming_routine=None,
    tile_shape=None,
    scheme=memtorch.bh.crossbar.Scheme.DoubleColumn,
)
crossbar_product = torch.matmul(
    a, operation(crossbars, lambda crossbar: crossbar.conductance_matrix)
)
print(f'Expected Product: {expected_product}')
print(f'Crossbar Product: {crossbar_product}')

MSE = torch.divide(torch.norm(expected_product.sub(crossbar_product)), torch.norm(expected_product))
print(f'MSE: {MSE}')
```

Why does this produce a scaled output?

```
Expected Product: tensor([[25., 25., 25., 25., 25.]])
Crossbar Product: tensor([[0.0004, 0.0004, 0.0004, 0.0004, 0.0004]])
MSE: 0.9999819993972778
```

Also by changing the value of `b = torch.full((5,5),newvalue)` the `crossbar_product does not change`

**Comment by coreylammie** [comment]
**Why does this produce a scaled output?**
The reason this produces a scaled output is that the elements of tensor `b` are encoded on the crossbar using conductance values which can be represented by each device, i.e., they are scaled and encoded between `1/r_off` and `1/r_on`. Ohms law is exploited to perform Vector-Matrix Multiplications (VMMs), so `I=VG` (assuming linear I/V characteristics and that line and source resistances are negligible/select devices are used). Elements of tensor `a` are encoded as Word Line (WL) voltages. 

Because encoded elements of tensor `b` are scaled, the resulting currents, i.e., `I`, must be scaled much that they are approximately equal to the desired product, `a x b`.

In your case, as only one unique value is encoded, so irrespective of this value, the programmed conductance values will not change, as they will all be at either `1/r_off` or `1/r_on`.

For more information regarding the underlying logic/approach, I would suggest reading Appendix A of the associated paper: https://www.sciencedirect.com/science/article/abs/pii/S0925231222002053. For a differential weight mapping scheme, (A.1) is commonly used.

**Also, I wondered if the same approach can be used to implement memristive multiplications in training.**
Sure- this is definitely possible. Although only inference is currently officially supported, a naïve programming routine is defined in: https://github.com/coreylammie/MemTorch/blob/master/memtorch/bh/crossbar/Program.py. This simulates a simple write-verify scheme, in which positive and negative voltages are used to write a specific conductance value to each device.

Additionally, arbitrary voltage waveforms can be applied to individual devices as follows (for the following examples the device in the first column and first row of the crossbar representing positive values is selected):

`crossbars[0].devices[0][0].simulate(voltage_waveform)`

Alternatively, the conductance of specific devices can be manually set as follows:

`crossbars[0].devices[0][0].g = g`

It is unlikely I will find time to do this myself in the immediate future, but MemTorch could be used to simulate _online end-to-end_ training routines of Deep Learning architectures.

**Comment by matifali** [comment]
Thank you for a detailed reply and pointing me in the right direction.
