### ISSUE TITLE
batch_input.unfold(1, size=self.kernel_size[0], step=self.stride[0]) RuntimeError: shape '[-1, 448]' is invalid for input of size 77824

### ISSUE THREAD

**Issue by Cigarskiiler** [coreylammie/MemTorch#153]
I encountered this problem in mapping neural networks to memristors：batch_input.unfold(1, size=self.kernel_size[0], step=self.stride[0])
RuntimeError: shape '[-1, 448]' is invalid for input of size 77824，How can I solve it

**Comment by spectacles9468** [comment]
Hi! I wanted to ask you about how you installed the memtorch library, because I'm getting error while building the wheel for memtorch-cpu. I tried it in colab. Did you do it on your local editor, conda, colab?
![image](https://github.com/coreylammie/MemTorch/assets/55502062/1fa0abf1-08ca-4aaf-ba51-cc60a91db11b)

![image](https://github.com/coreylammie/MemTorch/assets/55502062/2b10c7c5-7b8a-401a-aef7-9ef1ee37e39b)
