### ISSUE TITLE
Issues in installing memtorch

### ISSUE THREAD

**Issue by godatta** [coreylammie/MemTorch#38]
Cannot install memtorch. I am getting this error. I am using a conda environment.
![Screen Shot 2021-04-07 at 4 50 07 PM](https://user-images.githubusercontent.com/46044371/113948272-51b17a00-97c1-11eb-88e1-d92eb9bda429.png)

**Comment by godatta** [comment]
When I try installing memtorch from source (using python setup.py install and making CUDA=False), I cannot use memtorch either. When I try running the tutorial.ipynb, I get a module not found error.

**Comment by coreylammie** [comment]
Hi godatta,

Thanks for reaching out! I have just run the following in Collaboratory notebooks with no enabled hardware accelerators. Both appear to install successfully, when `CUDA_HOME` is not set.

Installation using pip:
```
!pip install memtorch-cpu
!printenv
```
Installation from source:
```
!git clone https://github.com/coreylammie/MemTorch
!git submodule update --init --recursive
%cd MemTorch
!python setup.py install
!printenv
```

To help me identify the issue, could you please provide the output when trying to install from source, and specify what operating system and version of pip/conda you are using? From your screenshot it looks like you are using linux and a conda environment with python=3.8. If so, could you please provide, in addition, the output of the following (depending on how python and pip are configured on your system, you may have to replace `pip` with `pip3` and  `python` with  `python3`):

Installation using pip:
```
pip install memtorch-cpu
printenv
```
Installation from source:
```
git clone https://github.com/coreylammie/MemTorch
git submodule update --init --recursive
cd MemTorch
python setup.py install
printenv
```

Kind Regards,

Corey.

**Comment by godatta** [comment]
Hi Corey,

Thanks for your reply. The OS and conda version you mentioned are correct. The output of the command you requested is attached below.

![Screen Shot 2021-04-08 at 1 21 36 AM](https://user-images.githubusercontent.com/46044371/113992930-c5c34080-9808-11eb-999a-23349275b7a6.png)

**Comment by coreylammie** [comment]
Hi godatta,

No problem at all! Looking at your original screenshot again, it appears that pip is trying to use an old cached version (1.0). The latest release on PyPi is 1.1.0.  I would suggest running the following commands, which should ensure that the latest release is downloaded, and that the cpu version is selected (in the first command, `--no-deps` avoids reinstalling  all dependencies):

`pip install --force-reinstall --no-cache-dir --no-deps memtorch-cpu==1.1.0`
`pip install memtorch-cpu==1.1.0` (to install any dependencies, if required)


If this does not work, could you please confirm that you originally tried to install memtorch using `pip install memtorch-cpu`, rather than `pip install memtorch`, and prove the output of the above commands?

**Comment by godatta** [comment]
Thanks! It works now!
