### ISSUE TITLE
The patching procedure is too slow.

### ISSUE THREAD

**Issue by Jize-W** [coreylammie/MemTorch#43]
Hello!@coreylammie 

When I use memtorch to patch ResNet18 model trained on CIFAR10, the procedure costs up to 2 hours, which is quite slow.  When I try the VGG16 in your tutorial, the same problem exists. I don't know if that is normal. Is there any way to speed up？

Besides,  I have put the model on GPU before the patching procedure, but when I test the patched model, the error exists:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

So I have to again put the PATCHED model on GPU for the program to run. But what is the reason?

**Comment by coreylammie** [comment]
Hi Jize-W,

Thank you for raising these concerns! Unfortunately, using PyTorch's Python API, when quantization and modular crossbars are modelled, operations cannot easily be parallelized. I have raised a new issue (#44) for the development of custom CUDA kernels to more effectively parallelize these operations. This should drastically improve performance by a few orders of magnitude.

If possible, could you please provide a minimal working example demonstrating the above error, or specify the exact line that raised the error so I can further investigate? 

In addition, I've re-opened issue (#22). Reducing the time required to patch/tune models is likely to take higher priority, however, timing/power estimates are still very much planned for eventual development/integration.

Kind Regards,

Corey.

**Comment by Philippe-Drolet** [comment]
Hello,

I am a master's student currently working in a team developing memristor technologies and we have started using memtorch to simulate our systems. In our team, we are mainly using passive crossbars and are trying to tune a basic linear MNIST NN to memtorch and it is taking a long time also (around two hours also). We were considering optimizing the process by transforming the simulate method of the data_driven model which we are using to work using np arrays of values. Before we do that however, we would like to know how you were planning on optimizing the patching procedure and where in the process you were so that we do not waste ressources or go against your implementation.

Thank you,

Philippe Drolet

**Comment by coreylammie** [comment]
Hi @Philippe-Drolet,

All contributions are welcome! Feel free to optimize the simulate method of the data_driven model and to submit a pull request. It would be greatly appreciated if you could create separate issues outlining (1) what could be improved and (2) any suggested steps/actions for improvement.

Currently, when modular crossbar tiles are used, `tile_matmul` in [memtorch/bh/crossbar/Tile.py](https://github.com/coreylammie/MemTorch/blob/023006a79a753a6a1335439423481495d02dc8ed/memtorch/bh/crossbar/Tile.py) greatly increases the runtime of forward passes (during inference and tuning calls). This is because lines 209-227 are not parallelized, rendering operation sequentially-bound.  

I have created a separate issue (#44) to resolve this, and I am currently developing C++/CUDA bindings, such as that defined in [memtorch/cpp/tile_matmul.cpp](https://github.com/coreylammie/MemTorch/blob/250e66c29df092a52793822dfed08b3523ce2940/memtorch/cpp/tile_matmul.cpp), for eventual integration. Once I have finished developing these bindings and CUDA kernels, the patching procedure should be such faster.

Kind Regards,

Corey.

**Comment by coreylammie** [comment]
In #66, C++ and CUDA bindings have been added to `tile_matmul` to greatly improve performance when patching/performing inference while modeling modular crossbar tiles. Using an NVIDIA GeForce GTX 1080, a tile shape of (25, 25), and two tensors of size (500, 500), the runtime of `tile_matmul` without quantization support is reduced by 2.45x and 5.48x, for CPU-bound and GPU-bound operation, respectively. With an ADC resolution of 4 bits and an overflow rate of 0.0, the runtime of `tile_matmul` with quantization support is reduced by 2.30x and 105.27x, for CPU-bound and GPU-bound operation, respectively.

| Implementation         | Runtime Without Quantization Support (s) | Runtime With Quantization Support (s) |
| ---------------------- | ---------------------------------------- | ------------------------------------- |
| Pure Python (Previous) | 6.917784                                 | 27.099764                             |
| C++ (CPU-bound)        | 2.822265                                 | 11.736974                             |
| CUDA (GPU-bound)       | 1.262861                                 | 0.2574267                             |

This should greatly reduce the time required to run the patching procedure for large networks.

**Comment by Jize-W** [comment]
Hi @coreylammie ,
I've downloaded version 1.1.2-gpu, and run the patching procedure for LeNet model trained on MNIST and ResNet18 model trained on CIFAR10. They cost 83.41 seconds and 11428.87 seconds respectively, which is still a long time. What may be the reason for this?

**Comment by coreylammie** [comment]
Hi @Jize-W,

I have profiled the first example provided in the default tutorial using `cProfile` (see [profile.zip](https://github.com/coreylammie/MemTorch/files/6835598/profile.zip) for the exact files used); this is using the MNIST test set. `snakeviz prof.prof` can be used to visualize the generated `.prof` file.

It looks like the most time consuming operations are as follows:

| ncalls         | tottime | percall   | cumtime | percall   | filename:lineno(function)                                 |
|----------------|---------|-----------|---------|-----------|-----------------------------------------------------------|
| 20016          | 122.1   | 0.006102  | 122.1   | 0.006102  | built-in method memtorch_cuda_bindings.tile_matmul |
| 20190          | 64.91   | 0.003215  | 64.91   | 0.003215  | built-in method tensor                            |
| 327681         | 6.61    | 2.017e-05 | 6.61    | 2.017e-05 | method 'item' of 'torch._C._TensorBase' objects  |
| 5243424/163851 | 3.847   | 2.348e-05 | 7.363   | 4.493e-05 | copy.py:132 (deepcopy)                                     |
| 50050          | 3.064   | 6.121e-05 | 3.466   | 6.925e-05 | Tile.py:35 (update_array)                                  |
| 50133          | 2.783   | 5.552e-05 | 2.783   | 5.552e-05 | method 'cpu' of 'torch._C._TensorBase' objects     |
| 8              | 2.713   | 0.3391    | 9.894   | 1.237     | Crossbar.py:100 (update)                                   |
| 162            | 1.659   | 0.01024   | 203.6   | 1.256     | Conv2d.py:131 (forward)                                    |
| 2              | 1.503   | 0.7516    | 1.503   | 0.7516    | built-in method conv2d                             |
| 20020          | 1.306   | 6.526e-05 | 1.306   | 6.526e-05 | utils.py:27(convert_range)                                |

During the forward (inference) call for memristive layers, `tile_matmul` takes 122s to execute (cumulatively), and `gen_tiles` takes 74.4s to execute (cumulatively). 

The overhead of calling `memtorch_cuda_bindings.tile_matmul` appears to be negligible. `gen_tiles` can definitely be optimized and implemented using C++/CUDA bindings, and the logic used prior to launching CUDA kernels in `memtorch_cuda_bindings.tile_matmul` can be simplified/made to be more efficient. 

I will endeavor to create a new branch in the future and develop C++/CUDA bindings for `gen_tiles`.  Ideally, end-to-end C++/CUDA routines should be developed to replace the `forward` routines of memristive layers.

**Comment by coreylammie** [comment]
Hi @Jize-W,

A quick update- I have merged #76 into master, which should further increase performance by generating crossbar tiles more efficiently using C++ bindings. 

For the eventual 1.1.2 release, I will integrate tile generation for inputs with existing bindings with `tile_matmul`.

**Comment by coreylammie** [comment]
This support was added in [https://github.com/coreylammie/MemTorch/releases/tag/v1.1.2](https://github.com/coreylammie/MemTorch/releases/tag/v1.1.2). I am closing this issue for the time being- please note that further optimizations are currently being made to speed-up operation, as even with CUDA operation, simulations can take a long time to run.

**Comment by sheep1222** [comment]
> 你好！@coreylammie
> 
> 当我使用 memtorch 修补在 CIFAR10 上训练的 ResNet18 模型时，整个过程最多需要 2 个小时，速度相当慢。当我尝试您教程中的 VGG16 时，也存在同样的问题。我不知道这是否正常。有什么办法可以加快速度吗？
> 
> 此外，我在修补程序之前已将模型放在GPU上，但是当我测试修补后的模型时，存在错误：
> 
> RuntimeError：预期所有张量都在同一设备上，但发​​现至少有两个设备，cuda：0和cpu！
> 
> 所以我必须再次将修补后的模型放在 GPU 上才能运行程序。但原因是什么呢？
您好，我想问的是，您在使用修补调整后的模型进行测试时，是否遇到过内存爆炸的问题？我用的模型和数据集是和您一样的。
